## 다층 퍼셉트론 - XOR - Tensorflow 1.x

In [2]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 2020
np.random.seed(seed)
tf.set_random_seed(seed)

In [5]:
# x, y의 데이터 값
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]]) 
y_data = np.array([0, 1, 1, 0]).reshape(-1,1)
print(x_data.shape, y_data.shape)

(4, 2) (4, 1)


In [6]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [7]:
# Layer 1
W1 = tf.Variable(tf.random_normal([2, 2]), dtype=tf.float32)
b1 = tf.Variable(tf.random_normal([2]), dtype=tf.float32)
L1 = tf.sigmoid(tf.matmul(X, W1) + b1)

In [8]:
# Layer 2
W2 = tf.Variable(tf.random_normal([2, 1]), dtype=tf.float32)
b2 = tf.Variable(tf.random_normal([1]), dtype=tf.float32)
hypo = tf.sigmoid(tf.matmul(L1, W2) + b2)

In [9]:
# Cost - Binary Cross Entropy
cost = -tf.reduce_mean(Y * tf.log(hypo) + (1.-Y) * tf.log(1.-hypo))

In [10]:
# Optimizer - Adam
lr = 0.1
train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)

In [11]:
# Accuracy 계산
predicted = tf.cast(hypo > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [12]:
# 학습
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
            
    # Accuracy report
    h, p, a = sess.run([hypo, predicted, accuracy], feed_dict={X: x_data, Y: y_data}) 
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")
    
    # Weight, bias
    W1_, b1_, W2_, b2_ = sess.run([W1, b1, W2, b2])
    print(f"\nW1:\n{W1_} \nb1:\n{b1_} \nW2:\n{W2_}\nb1:\n{b2_}")

0 0.7744102
1000 0.0011717796
2000 0.0003451295
3000 0.00015246615
4000 7.833867e-05
5000 4.330377e-05
6000 2.488527e-05
7000 1.4618154e-05
8000 8.717219e-06
9000 5.20052e-06
10000 3.129249e-06

Hypothesis:
[[3.7819730e-06]
 [9.9999654e-01]
 [9.9999642e-01]
 [1.7323360e-06]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

W1:
[[  9.317337 -13.68283 ]
 [  9.299182 -13.665263]] 
b1:
[-14.443806   6.410648] 
W2:
[[-26.396774]
 [-25.256826]]
b1:
[12.730124]
